/**
 * supabase/functions/_shared/fernet.ts
 *
 * Fernet-compatible encryption (Python `cryptography.fernet.Fernet`).
 *
 * Token format (urlsafe-base64 of):
 *   version(1) | timestamp(8 BE) | iv(16) | ciphertext | hmac(32)
 *
 * Key format: urlsafe-base64 of 32 raw bytes; first 16 = HMAC signing key,
 * last 16 = AES-128-CBC encryption key. Generated by
 * `cryptography.fernet.Fernet.generate_key()`.
 *
 * Implementation uses Web Crypto (AES-CBC + HMAC-SHA256) to stay free of the
 * `npm:fernet` package, which has Deno npm-compat issues around Buffer and
 * the legacy `crypto` module. The format matches the Python implementation
 * byte-for-byte so tokens written by either side round-trip cleanly.
 */

// ── base64url ────────────────────────────────────────────────────────────────

function base64urlDecode(str: string): Uint8Array {
  const base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64 + "==".slice(0, (4 - (base64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function base64urlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_");
}

function concatBytes(...arrays: Uint8Array[]): Uint8Array {
  const total = arrays.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const arr of arrays) {
    out.set(arr, offset);
    offset += arr.length;
  }
  return out;
}

function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

// ── Key split ────────────────────────────────────────────────────────────────

function splitKey(keyBase64url: string): { signingKey: Uint8Array; encryptionKey: Uint8Array } {
  const keyBytes = base64urlDecode(keyBase64url);
  if (keyBytes.length !== 32) {
    throw new Error(`Fernet key must be 32 bytes, got ${keyBytes.length}`);
  }
  return {
    signingKey: keyBytes.slice(0, 16),
    encryptionKey: keyBytes.slice(16, 32),
  };
}

// ── Encrypt ─────────────────────────────────────────────────────────────────

/**
 * Encrypt a UTF-8 plaintext under a Fernet key.
 * Returns a urlsafe-base64 token; format is interoperable with
 * `cryptography.fernet.Fernet.encrypt`.
 */
export async function fernetEncrypt(
  keyBase64url: string,
  plaintext: string,
): Promise<string> {
  const { signingKey, encryptionKey } = splitKey(keyBase64url);

  const ts = Math.floor(Date.now() / 1000);
  const timeBytes = new Uint8Array(8);
  const view = new DataView(timeBytes.buffer);
  view.setUint32(0, Math.floor(ts / 0x100000000), false);
  view.setUint32(4, ts >>> 0, false);

  const iv = crypto.getRandomValues(new Uint8Array(16));

  const aesKey = await crypto.subtle.importKey(
    "raw",
    encryptionKey,
    { name: "AES-CBC" },
    false,
    ["encrypt"],
  );
  const ciphertextBuf = await crypto.subtle.encrypt(
    { name: "AES-CBC", iv },
    aesKey,
    new TextEncoder().encode(plaintext),
  );
  const ciphertext = new Uint8Array(ciphertextBuf);

  const version = new Uint8Array([0x80]);
  const toSign = concatBytes(version, timeBytes, iv, ciphertext);

  const hmacKey = await crypto.subtle.importKey(
    "raw",
    signingKey,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const hmac = new Uint8Array(await crypto.subtle.sign("HMAC", hmacKey, toSign));

  return base64urlEncode(concatBytes(version, timeBytes, iv, ciphertext, hmac));
}

// ── Decrypt ─────────────────────────────────────────────────────────────────

/**
 * Decrypt a Fernet token under the same key. Throws on:
 *   - malformed input
 *   - invalid version byte
 *   - HMAC mismatch (constant-time compare)
 *   - invalid PKCS#7 padding
 *
 * TTL is intentionally NOT enforced: callers in this repo decrypt long-lived
 * refresh tokens that pre-date any sensible TTL. If a caller needs TTL, wrap
 * the timestamp check itself rather than relying on this helper.
 */
export async function fernetDecrypt(
  keyBase64url: string,
  token: string,
): Promise<string> {
  const { signingKey, encryptionKey } = splitKey(keyBase64url);

  const tokenBytes = base64urlDecode(token);
  if (tokenBytes.length < 1 + 8 + 16 + 16 + 32) {
    throw new Error("Fernet token too short");
  }
  if (tokenBytes[0] !== 0x80) {
    throw new Error(`Invalid Fernet version byte: 0x${tokenBytes[0].toString(16)}`);
  }

  const timeBytes = tokenBytes.slice(1, 9);
  const iv = tokenBytes.slice(9, 25);
  const ciphertext = tokenBytes.slice(25, tokenBytes.length - 32);
  const hmac = tokenBytes.slice(tokenBytes.length - 32);

  const version = new Uint8Array([0x80]);
  const toSign = concatBytes(version, timeBytes, iv, ciphertext);

  const hmacKey = await crypto.subtle.importKey(
    "raw",
    signingKey,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const expectedHmac = new Uint8Array(await crypto.subtle.sign("HMAC", hmacKey, toSign));
  if (!timingSafeEqual(expectedHmac, hmac)) {
    throw new Error("Fernet HMAC mismatch");
  }

  const aesKey = await crypto.subtle.importKey(
    "raw",
    encryptionKey,
    { name: "AES-CBC" },
    false,
    ["decrypt"],
  );
  const plaintextBuf = await crypto.subtle.decrypt(
    { name: "AES-CBC", iv },
    aesKey,
    ciphertext,
  );
  const padded = new Uint8Array(plaintextBuf);

  // PKCS#7 unpadding (1-16 bytes).
  if (padded.length === 0 || padded.length % 16 !== 0) {
    throw new Error("Invalid Fernet ciphertext length");
  }
  const padLen = padded[padded.length - 1];
  if (padLen < 1 || padLen > 16) {
    throw new Error("Invalid Fernet PKCS#7 padding length");
  }
  for (let i = padded.length - padLen; i < padded.length; i++) {
    if (padded[i] !== padLen) throw new Error("Invalid Fernet PKCS#7 padding");
  }
  const unpadded = padded.slice(0, padded.length - padLen);

  return new TextDecoder().decode(unpadded);
}
