name: CI - Atendente API

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "services/atendente_api/**"
      - "libs/**"
  pull_request:
    paths:
      - "services/atendente_api/**"
      - "libs/**"

jobs:
  build-and-test:
    name: Build and Test Service
    runs-on: ubuntu-latest

    defaults:
      run:
        # Define o diretório de trabalho padrão para os comandos
        working-directory: ./services/atendente_api

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3. Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2 # Use uma versão estável

      - name: 4. Instalar Dependências com Poetry
        run: poetry install --no-interaction --no-root

      - name: 5. Executar Testes com Pytest
        run: |
          poetry run pytest
