# Estágio 1: Build da Imagem Base
FROM python:3.11-slim as builder

# Define o WORKDIR e instala o Poetry
WORKDIR /app
RUN pip install poetry

# Copia os arquivos de dependência e instala
# O Poetry é responsável por criar o ambiente
COPY pyproject.toml poetry.lock /app/
RUN poetry install --no-root --only main

# Estágio 2: Imagem Final de Produção (Slim)
FROM python:3.11-slim as production

# Define variáveis de ambiente Vizu
ENV PYTHONUNBUFFERED 1
ENV VIZU_SERVICE_NAME=data-ingestion-api
ENV VIZU_ENVIRONMENT=production

# Copia os pacotes instalados e o código-fonte
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY src/ /app/src/

# O ponto crítico: O comando deve apontar para o novo pacote raiz
# Estrutura: [pacote_raiz].[subpasta_core].[módulo]:[instância_fastapi]
CMD ["uvicorn", "data_ingestion_api.core.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Opcional: Expõe a porta
EXPOSE 8000