-- 20260619_shared_business_memory_meta.sql
-- Fase 4 / T4.2: Shared Business Memory Meta — dados operacionais dos agentes
--
-- Tabela irmã da shared_business_memory, armazena metadados operacionais
-- gerados pelos agentes: outputs de síntese, mapeamentos de deduplicação
-- e sumários de knowledge graph.
--
-- NÃO aplicar automaticamente. Lucas revisa.

BEGIN;

CREATE TABLE IF NOT EXISTS public.shared_business_memory_meta (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    client_id   uuid NOT NULL
                REFERENCES public.clientes_blu(client_id)
                ON DELETE CASCADE,

    -- Tipo de artefato operacional gerado por um agente
    entity_type text NOT NULL
                CHECK (entity_type IN (
                    'synthesis_output', 'dedup_mapping', 'kg_summary'
                )),

    -- Nome da entidade de negócio à qual este metadado se refere
    entity_name text NOT NULL,

    -- Chave do metadado (ex: "resumo_semanal", "mapa_skills_duplicados")
    key         text NOT NULL
                CHECK (length(key) >= 1 AND length(key) <= 256),

    -- Valor do metadado (JSONB — estrutura varia por entity_type)
    value       jsonb NOT NULL DEFAULT '{}'::jsonb,

    -- Metadados de proveniência
    source      text NOT NULL DEFAULT 'system'
                CHECK (source IN (
                    'manual', 'memory_agent', 'specialist', 'migration', 'system'
                )),
    confidence  numeric NOT NULL DEFAULT 1.0
                CHECK (confidence >= 0.0 AND confidence <= 1.0),
    metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,

    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),

    -- Cada (client_id, entity_type, entity_name, key) é único
    CONSTRAINT uq_sbm_meta_entry
        UNIQUE (client_id, entity_type, entity_name, key)
);

COMMENT ON TABLE public.shared_business_memory_meta IS
    'Shared Business Memory Meta — operational metadata generated by agents. '
    'Stores synthesis outputs, deduplication mappings, and knowledge graph summaries. '
    'Sister table to shared_business_memory.';
COMMENT ON COLUMN public.shared_business_memory_meta.entity_type IS
    'Operational artifact type: synthesis_output | dedup_mapping | kg_summary';
COMMENT ON COLUMN public.shared_business_memory_meta.entity_name IS
    'Business entity this metadata refers to (e.g. client name, skill name)';
COMMENT ON COLUMN public.shared_business_memory_meta.key IS
    'Metadata key — e.g. resumo_semanal, mapa_skills_duplicados';
COMMENT ON COLUMN public.shared_business_memory_meta.source IS
    'Provenance: manual | memory_agent | specialist | migration | system';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Primary query: buscar metadados por entidade
CREATE INDEX IF NOT EXISTS idx_sbm_meta_entity
    ON public.shared_business_memory_meta (client_id, entity_type, entity_name);

-- Lookup por chave específica
CREATE INDEX IF NOT EXISTS idx_sbm_meta_key
    ON public.shared_business_memory_meta (client_id, entity_type, entity_name, key);

-- Busca textual nas chaves (para descoberta de metadados)
CREATE INDEX IF NOT EXISTS idx_sbm_meta_key_trgm
    ON public.shared_business_memory_meta USING gin (key gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Updated-at trigger
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_shared_business_memory_meta_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_shared_business_memory_meta_updated_at
    ON public.shared_business_memory_meta;
CREATE TRIGGER trg_shared_business_memory_meta_updated_at
    BEFORE UPDATE ON public.shared_business_memory_meta
    FOR EACH ROW
    EXECUTE FUNCTION public.update_shared_business_memory_meta_updated_at();

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE public.shared_business_memory_meta ENABLE ROW LEVEL SECURITY;

CREATE POLICY client_own_shared_memory_meta
    ON public.shared_business_memory_meta
    AS PERMISSIVE
    FOR ALL
    TO public
    USING (
        client_id = (current_setting('app.client_id'::text, true))::uuid
    );

COMMIT;
