"""Adiciona tabelas FonteDeDados e CredencialServicoExterno

Revision ID: 1721df8bc2e1
Revises: f37c6b61ca60
Create Date: 2025-10-01 15:12:41.696173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1721df8bc2e1'
down_revision: Union[str, Sequence[str], None] = 'f37c6b61ca60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
