"""initial_schema_from_models
Revision ID: 97f287628115
Revises: e60514203590
Create Date: 2025-11-26 14:29:11.173318

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '97f287628115'
down_revision = 'e60514203590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
