"""Criação das tabelas iniciais

Revision ID: f37c6b61ca60
Revises: 
Create Date: 2025-10-01 14:29:17.594194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37c6b61ca60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_vizu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('tipo_cliente', sa.Enum('EXTERNO', 'INTERNO', name='tipo_cliente_enum'), nullable=False),
    sa.Column('tier', sa.Enum('SME', 'ENTERPRISE', name='tier_cliente_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_vizu_api_key'), 'cliente_vizu', ['api_key'], unique=True)
    op.create_table('cliente_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('id_externo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('metadados', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['cliente_vizu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_final_id_externo'), 'cliente_final', ['id_externo'], unique=False)
    op.create_table('configuracao_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('prompt_base', sa.Text(), nullable=True),
    sa.Column('horario_funcionamento', sa.JSON(), nullable=True),
    sa.Column('ferramenta_rag_habilitada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['cliente_vizu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_vizu_id')
    )
    op.create_table('conversa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_final_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_final_id'], ['cliente_final.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.UUID(), nullable=False),
    sa.Column('remetente', sa.Enum('USER', 'AI', name='remetente_enum'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('conversa')
    op.drop_table('configuracao_negocio')
    op.drop_index(op.f('ix_cliente_final_id_externo'), table_name='cliente_final')
    op.drop_table('cliente_final')
    op.drop_index(op.f('ix_cliente_vizu_api_key'), table_name='cliente_vizu')
    op.drop_table('cliente_vizu')
    # ### end Alembic commands ###
