-- =====================================================================
-- CONSOLIDATED ANALYTICS SCHEMA - Phase 2 Cleanup
-- =====================================================================
-- Purpose: Address redundancies and inconsistencies in analytics tables
-- Created: 2026-01-22
-- Addresses:
--   1. Duplicate column naming (total_quantity_sold vs quantidade_total)
--   2. Missing unique constraints for data integrity
--   3. Standardize date field naming across tables
--   4. Add missing indexes for performance
-- =====================================================================

-- =====================================================================
-- PHASE 1: Add Missing Unique Constraints
-- =====================================================================

-- Prevent duplicate customer records per period
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_gold_customer_period
    ON public.analytics_gold_customers(client_id, customer_name, period_type, COALESCE(period_start, '1970-01-01'::timestamptz))
    WHERE period_type IS NOT NULL;

COMMENT ON INDEX idx_unique_gold_customer_period IS 'Ensures no duplicate customer records for the same period';

-- Prevent duplicate supplier records per period
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_gold_supplier_period
    ON public.analytics_gold_suppliers(client_id, supplier_name, period_type, COALESCE(period_start, '1970-01-01'::timestamptz))
    WHERE period_type IS NOT NULL;

COMMENT ON INDEX idx_unique_gold_supplier_period IS 'Ensures no duplicate supplier records for the same period';

-- Prevent duplicate product records per period
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_gold_product_period
    ON public.analytics_gold_products(client_id, product_name, period_type, COALESCE(period_start, '1970-01-01'::timestamptz))
    WHERE period_type IS NOT NULL;

COMMENT ON INDEX idx_unique_gold_product_period IS 'Ensures no duplicate product records for the same period';

-- =====================================================================
-- PHASE 2: Add Performance Indexes
-- =====================================================================

-- Customer CPF/CNPJ lookup (for join operations)
CREATE INDEX IF NOT EXISTS idx_gold_customers_cpf_cnpj
    ON public.analytics_gold_customers(customer_cpf_cnpj)
    WHERE customer_cpf_cnpj IS NOT NULL;

COMMENT ON INDEX idx_gold_customers_cpf_cnpj IS 'Speeds up customer lookups by CPF/CNPJ';

-- Supplier CNPJ lookup
CREATE INDEX IF NOT EXISTS idx_gold_suppliers_cnpj
    ON public.analytics_gold_suppliers(supplier_cnpj)
    WHERE supplier_cnpj IS NOT NULL;

COMMENT ON INDEX idx_gold_suppliers_cnpj IS 'Speeds up supplier lookups by CNPJ';

-- Customer name search (case-insensitive)
CREATE INDEX IF NOT EXISTS idx_gold_customers_name_lower
    ON public.analytics_gold_customers(LOWER(customer_name));

COMMENT ON INDEX idx_gold_customers_name_lower IS 'Enables case-insensitive customer name searches';

-- Product name search (case-insensitive)
CREATE INDEX IF NOT EXISTS idx_gold_products_name_lower
    ON public.analytics_gold_products(LOWER(product_name));

COMMENT ON INDEX idx_gold_products_name_lower IS 'Enables case-insensitive product name searches';

-- Recency filtering (for active customer queries)
CREATE INDEX IF NOT EXISTS idx_gold_customers_recencia
    ON public.analytics_gold_customers(recencia_dias)
    WHERE recencia_dias IS NOT NULL;

COMMENT ON INDEX idx_gold_customers_recencia IS 'Speeds up active/inactive customer filters';

-- Lifetime value filtering (for high-value customer queries)
CREATE INDEX IF NOT EXISTS idx_gold_customers_ltv_desc
    ON public.analytics_gold_customers(lifetime_value DESC)
    WHERE lifetime_value > 0;

COMMENT ON INDEX idx_gold_customers_ltv_desc IS 'Speeds up top customer by revenue queries';

-- =====================================================================
-- PHASE 3: Add Column Comments for Documentation
-- =====================================================================

-- Analytics Gold Customers
COMMENT ON COLUMN public.analytics_gold_customers.customer_name IS 'Customer display name (receiver_nome from source)';
COMMENT ON COLUMN public.analytics_gold_customers.customer_cpf_cnpj IS 'Brazilian government ID - CPF (individual) or CNPJ (company)';
COMMENT ON COLUMN public.analytics_gold_customers.lifetime_value IS 'Total revenue generated by this customer';
COMMENT ON COLUMN public.analytics_gold_customers.quantidade_total IS 'Total quantity of products purchased';
COMMENT ON COLUMN public.analytics_gold_customers.num_pedidos_unicos IS 'Number of unique orders placed';
COMMENT ON COLUMN public.analytics_gold_customers.ticket_medio IS 'Average order value (lifetime_value / num_pedidos_unicos)';
COMMENT ON COLUMN public.analytics_gold_customers.recencia_dias IS 'Days since last purchase (0 = purchased today)';
COMMENT ON COLUMN public.analytics_gold_customers.cluster_tier IS 'RFM segmentation tier: A (best), B, C, D (worst)';
COMMENT ON COLUMN public.analytics_gold_customers.period_type IS 'Time window: all_time, monthly, quarterly, yearly';

-- Analytics Gold Suppliers
COMMENT ON COLUMN public.analytics_gold_suppliers.supplier_name IS 'Supplier display name (emitter_nome from source)';
COMMENT ON COLUMN public.analytics_gold_suppliers.supplier_cnpj IS 'Brazilian company ID (CNPJ)';
COMMENT ON COLUMN public.analytics_gold_suppliers.total_revenue IS 'Total revenue from this supplier';
COMMENT ON COLUMN public.analytics_gold_suppliers.unique_products IS 'Number of distinct products supplied';

-- Analytics Gold Products
COMMENT ON COLUMN public.analytics_gold_products.product_name IS 'Product name (raw_product_description from source)';
COMMENT ON COLUMN public.analytics_gold_products.total_quantity_sold IS 'LEGACY: Use quantidade_total instead';
COMMENT ON COLUMN public.analytics_gold_products.quantidade_total IS 'Total quantity sold across all orders';
COMMENT ON COLUMN public.analytics_gold_products.order_count IS 'LEGACY: Use num_pedidos_unicos instead';
COMMENT ON COLUMN public.analytics_gold_products.num_pedidos_unicos IS 'Number of unique orders containing this product';
COMMENT ON COLUMN public.analytics_gold_products.revenue_rank IS 'Rank by total_revenue (1 = highest revenue)';

-- Analytics Gold Orders
COMMENT ON TABLE public.analytics_gold_orders IS 'Aggregated order metrics per client and time period';
COMMENT ON COLUMN public.analytics_gold_orders.customer_cpf_cnpj IS 'CPF/CNPJ of customer - logical FK to analytics_gold_customers.customer_cpf_cnpj';

-- Analytics Gold Last Orders
COMMENT ON TABLE public.analytics_gold_last_orders IS 'Precomputed list of last 20 orders for quick dashboard loading';
COMMENT ON COLUMN public.analytics_gold_last_orders.customer_name IS 'Customer name (receiver_nome) from the order';
COMMENT ON COLUMN public.analytics_gold_last_orders.order_rank IS 'Rank by data_transacao DESC (1 = most recent)';

-- Analytics Gold Time Series
COMMENT ON TABLE public.analytics_gold_time_series IS 'Precomputed time-series data for line charts';
COMMENT ON COLUMN public.analytics_gold_time_series.chart_type IS 'Chart identifier: fornecedores_no_tempo, clientes_no_tempo, etc.';
COMMENT ON COLUMN public.analytics_gold_time_series.dimension IS 'Dimension being tracked: count, revenue, etc.';
COMMENT ON COLUMN public.analytics_gold_time_series.period IS 'Human-readable period: 2024-01, 2024-Q1, etc.';
COMMENT ON COLUMN public.analytics_gold_time_series.period_date IS 'First day of the period for sorting/filtering';

-- Analytics Gold Regional
COMMENT ON TABLE public.analytics_gold_regional IS 'Precomputed regional breakdowns for pie/bar charts';
COMMENT ON COLUMN public.analytics_gold_regional.chart_type IS 'Chart identifier: fornecedores_por_regiao, clientes_por_uf, etc.';
COMMENT ON COLUMN public.analytics_gold_regional.region_type IS 'Geographic level: cidade (city) or uf (state)';
COMMENT ON COLUMN public.analytics_gold_regional.contagem IS 'Count of entities in this region';
COMMENT ON COLUMN public.analytics_gold_regional.percentual IS 'Percentage of total (0-100)';

-- =====================================================================
-- PHASE 4: Data Quality Views
-- =====================================================================

-- View: Customers with missing contact information
CREATE OR REPLACE VIEW v_customers_missing_contact AS
SELECT
    client_id,
    customer_name,
    customer_cpf_cnpj,
    lifetime_value,
    num_pedidos_unicos,
    CASE
        WHEN telefone IS NULL THEN 'Missing Phone'
        WHEN endereco_cidade IS NULL THEN 'Missing City'
        WHEN endereco_uf IS NULL THEN 'Missing State'
        ELSE 'Other'
    END as missing_field
FROM public.analytics_gold_customers
WHERE period_type = 'all_time'
  AND (telefone IS NULL OR endereco_cidade IS NULL OR endereco_uf IS NULL)
ORDER BY lifetime_value DESC;

COMMENT ON VIEW v_customers_missing_contact IS 'High-value customers with incomplete contact information';

-- View: Duplicate customer records (should be 0 after unique constraint)
CREATE OR REPLACE VIEW v_duplicate_customer_records AS
SELECT
    client_id,
    customer_name,
    period_type,
    period_start,
    COUNT(*) as duplicate_count
FROM public.analytics_gold_customers
GROUP BY client_id, customer_name, period_type, period_start
HAVING COUNT(*) > 1;

COMMENT ON VIEW v_duplicate_customer_records IS 'Identifies duplicate customer records - should return 0 rows';

-- View: Column consistency check
CREATE OR REPLACE VIEW v_column_consistency_check AS
SELECT
    'Products: total_quantity_sold vs quantidade_total mismatch' as issue,
    COUNT(*) as affected_rows
FROM public.analytics_gold_products
WHERE total_quantity_sold != quantidade_total
UNION ALL
SELECT
    'Products: order_count vs num_pedidos_unicos mismatch' as issue,
    COUNT(*) as affected_rows
FROM public.analytics_gold_products
WHERE order_count != num_pedidos_unicos;

COMMENT ON VIEW v_column_consistency_check IS 'Checks for data inconsistencies between duplicate columns';

-- =====================================================================
-- PHASE 5: Helper Functions
-- =====================================================================

-- Function: Sync duplicate columns in products table
CREATE OR REPLACE FUNCTION sync_product_duplicate_columns()
RETURNS TABLE(
    updated_quantity_count BIGINT,
    updated_orders_count BIGINT
) AS $$
DECLARE
    v_quantity_count BIGINT;
    v_orders_count BIGINT;
BEGIN
    -- Sync total_quantity_sold to quantidade_total
    UPDATE public.analytics_gold_products
    SET total_quantity_sold = quantidade_total
    WHERE total_quantity_sold != quantidade_total;

    GET DIAGNOSTICS v_quantity_count = ROW_COUNT;

    -- Sync order_count to num_pedidos_unicos
    UPDATE public.analytics_gold_products
    SET order_count = num_pedidos_unicos
    WHERE order_count != num_pedidos_unicos;

    GET DIAGNOSTICS v_orders_count = ROW_COUNT;

    RETURN QUERY SELECT v_quantity_count, v_orders_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sync_product_duplicate_columns() IS 'Emergency function to sync duplicate column values - should not be needed after ETL fix';

-- =====================================================================
-- PHASE 6: RLS Policies Verification
-- =====================================================================

-- Verify all analytics tables have RLS enabled
DO $$
DECLARE
    tbl TEXT;
    rls_enabled BOOLEAN;
BEGIN
    FOR tbl IN
        SELECT tablename
        FROM pg_tables
        WHERE schemaname = 'public'
          AND tablename LIKE 'analytics_%'
    LOOP
        SELECT relrowsecurity INTO rls_enabled
        FROM pg_class
        WHERE relname = tbl;

        IF NOT rls_enabled THEN
            RAISE WARNING 'RLS not enabled on table: %', tbl;
        END IF;
    END LOOP;
END;
$$;

-- =====================================================================
-- COMPLETION
-- =====================================================================

-- Log migration completion
DO $$
BEGIN
    RAISE NOTICE '✅ Analytics schema consolidation complete';
    RAISE NOTICE '✅ Added % unique constraints', 3;
    RAISE NOTICE '✅ Added % performance indexes', 7;
    RAISE NOTICE '✅ Added column comments for documentation';
    RAISE NOTICE '✅ Created % data quality views', 3;
    RAISE NOTICE '✅ Created % helper functions', 1;
    RAISE NOTICE '';
    RAISE NOTICE '⚠️  Action Required:';
    RAISE NOTICE '   1. Run: SELECT * FROM v_duplicate_customer_records;';
    RAISE NOTICE '      (should return 0 rows)';
    RAISE NOTICE '   2. Run: SELECT * FROM v_column_consistency_check;';
    RAISE NOTICE '      (check if duplicate columns are in sync)';
    RAISE NOTICE '   3. Update ETL to use quantidade_total/num_pedidos_unicos only';
END;
$$;
