-- =============================================================================
-- Migration: fix Excel date serial parsing in sincronizar_csv_cliente
-- Date: 2026-05-18
-- Problem: XLSX columns formatted as "Number" (not "Date") in Excel store dates
--          as integer serials (e.g. 45912 = 2025-09-12). cellDates:true skips
--          these, so they arrive as the string "45912" and silently fail all
--          date casts, leaving data_competencia_id NULL for every row.
-- Fix: three-tier fallback in the date parser:
--   1. Standard Postgres DATE cast (ISO format)
--   2. to_date(v, 'DD/MM/YYYY') for Brazilian text format
--   3. DATE '1899-12-30' + serial::INT for Excel numeric serials
--      (with sanity range 1970-2100 to avoid misinterpreting real integers)
-- Companion fix: run-csv-etl XLSX parser also converts numeric serials at
--   ingestion so future staging rows already contain ISO date strings.
-- Applied directly via MCP as: fix_sincronizar_csv_excel_date_serial
-- =============================================================================
