-- Migration: Promote enriched metadata to first-class columns and enhance FTS
-- Reason: theme, word_cloud, usage_context are generated by process-document EF
-- but stored only in JSONB metadata. Promoting them enables:
--   - theme: hard filter in hybrid_match_documents (like categories)
--   - word_cloud + usage_context: enrich FTS tsvector for better keyword matching

-- ════════════════════════════════════════════════════════════
-- 1. Add new columns
-- ════════════════════════════════════════════════════════════

ALTER TABLE vector_db.document_chunks
  ADD COLUMN IF NOT EXISTS theme TEXT,
  ADD COLUMN IF NOT EXISTS word_cloud TEXT[],
  ADD COLUMN IF NOT EXISTS usage_context TEXT;

-- ════════════════════════════════════════════════════════════
-- 2. Backfill from existing JSONB metadata
-- ════════════════════════════════════════════════════════════

-- theme: direct text extraction
UPDATE vector_db.document_chunks
SET theme = metadata->>'theme'
WHERE metadata->>'theme' IS NOT NULL AND theme IS NULL;

-- word_cloud: JSONB array → TEXT[]
UPDATE vector_db.document_chunks
SET word_cloud = ARRAY(
  SELECT jsonb_array_elements_text(metadata->'word_cloud')
)
WHERE metadata->'word_cloud' IS NOT NULL
  AND jsonb_typeof(metadata->'word_cloud') = 'array'
  AND word_cloud IS NULL;

-- usage_context: direct text extraction
UPDATE vector_db.document_chunks
SET usage_context = metadata->>'usage_context'
WHERE metadata->>'usage_context' IS NOT NULL AND usage_context IS NULL;

-- ════════════════════════════════════════════════════════════
-- 3. Add indexes for the new columns
-- ════════════════════════════════════════════════════════════

-- B-tree on theme for equality filters (like category)
CREATE INDEX IF NOT EXISTS idx_chunks_theme ON vector_db.document_chunks USING btree (theme);

-- GIN on word_cloud for array containment queries (@> / &&)
CREATE INDEX IF NOT EXISTS idx_chunks_word_cloud ON vector_db.document_chunks USING gin (word_cloud);

-- ════════════════════════════════════════════════════════════
-- 4. Enhance generate_fts() to include word_cloud + usage_context
--    This enriches the tsvector so keyword search automatically
--    benefits from the metadata without extra SQL parameters.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION vector_db.generate_fts()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.fts := to_tsvector(
    'portuguese',
    vector_db.immutable_unaccent(
      -- Main content (weight A — most important)
      NEW.content
      -- Append word_cloud terms (weight boost for salient keywords)
      || ' ' || COALESCE(array_to_string(NEW.word_cloud, ' '), '')
      -- Append usage_context (intent description helps intent-matching queries)
      || ' ' || COALESCE(NEW.usage_context, '')
    )
  );
  RETURN NEW;
END;
$function$;

-- ════════════════════════════════════════════════════════════
-- 5. Rebuild FTS for all existing chunks so they include
--    word_cloud + usage_context in their tsvector
-- ════════════════════════════════════════════════════════════

UPDATE vector_db.document_chunks
SET fts = to_tsvector(
  'portuguese',
  vector_db.immutable_unaccent(
    content
    || ' ' || COALESCE(array_to_string(word_cloud, ' '), '')
    || ' ' || COALESCE(usage_context, '')
  )
)
WHERE word_cloud IS NOT NULL OR usage_context IS NOT NULL;
